// Code generated by `telnyx-edge types`. DO NOT EDIT.

import type { ActorNamespace as __TelnyxActorNamespace } from "@telnyx/edge-runtime";
import type { FleetInventory } from "./src/index";

declare global {
  interface Env {
    FLEET: __TelnyxActorNamespace<FleetInventory>;
  }
}

declare module "@telnyx/edge-runtime" {
  interface Env {
    FLEET: __TelnyxActorNamespace<FleetInventory>;
  }
}

export {};
