// Code generated by `telnyx-edge types`. DO NOT EDIT.

import type { ActorNamespace as __TelnyxActorNamespace, KvNamespace as __TelnyxKvNamespace } from "@telnyx/edge-runtime";
import type { CallSession } from "./src/index";

declare global {
  interface Env {
    SESSIONS: __TelnyxActorNamespace<CallSession>;
    WADEEA_CONFIG: __TelnyxKvNamespace;
  }
}

declare module "@telnyx/edge-runtime" {
  interface Env {
    SESSIONS: __TelnyxActorNamespace<CallSession>;
    WADEEA_CONFIG: __TelnyxKvNamespace;
  }
}

export {};
